#!/bin/bash
# 20. Излистајте ги во посебна датотека сите датотеки во вашиот домашен
# директориум кои се модифицирани во тековниот ден (потешка но
# незадолжителна варијанта: модифицирани во последните 24 часа. Уште
# потешка: наместо во домашниот директориум, во неговото дрво).

[ -f "~/modificirani" ] && rm "~/modificirani"

SEGA=`date +"%s"`
echo $SEGA
for item in ~/*
do
    MOD=`date -r "$item" +"%s"`
    DIF=`expr $SEGA - $MOD`
    DIFHRS=`expr $DIF / 3600`
    if [ $DIFHRS -lt 24 ]; then
        echo "$item: $MOD | $DIF | $DIFHRS" >> ~/modificirani
    fi
done
