#!/bin/bash
# 21. Направете, во вид на скрипта, команда за безбедно бришење. Датотеките
# дадени како аргументи на скриптата не се отстрануваат, туку се преместуваат во
# директориумот ~/gjubre.На крај, скриптата ги отстранува сите датотеки од овој
# директориум кои се постари од еден ден. 

[ -d "~/gjubre" ] || mkdir ~/gjubre

SEGA=`date +"%s"`

for item in $*
do
    echo $item
    cp -p $item ~/gjubre
done

for item in ~/gjubre/*
do
    MOD=`date -r $item +"%s"`
    DIF=`expr $SEGA - $MOD`
    DIFH=`expr $DIF / 3600`
    echo "$MOD $DIFH"
    [ $DIFH -gt 10 ] && rm $item
done
