#!/bin/bash
# 19. Да се изведе рекурзивно листање на домашниот именик на следниов начин:
# прво се печатат датотеките и подимениците на тековниот именик, па потоа се
# печати: “Vo imenikot imenik se naogjaat: f1,f2,…” (значи, преордер поминување на
# домашниот директориум). Излезот треба да се наоѓа во датотеката listing.
echo "Working with $1"
DIR=$1

echo "Vo $DIR se naogjaat:" >> listing
ls -l $DIR >> listing
for item in $DIR/*
do
    if [[ -d $item ]]; then
        echo "going into $item"
        ./zadaca9 $item
    fi
done
